[project]
name = "stonks-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asciichartpy>=1.5.25",
    "click>=8.3.0",
    "pandas>=2.3.3",
    "rich>=14.2.0",
    "typer>=0.19.2",
]
